# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  host: localhost
  username: postgres
  password:

production:
  <<: *default
  adapter: postgresql
  host: db
  username: postgres
  password:
  